### ISSUE TITLE
Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by scotthollandjr** [aksonov/react-native-router-flux#1926]
### Version
```
"firebase": "3.6.8",
"lodash": "^4.17.4",
"react": "15.4.2",
"react-native": "0.41.1",
"react-native-maps": "git+https://github.com/airbnb/react-native-maps.git",
"react-native-router-flux": "^3.37.0",
"react-native-vector-icons": "4.0.0",
"react-redux": "5.0.2",
"redux": "3.6.0",
"redux-thunk": "2.2.0"
```

### Expected behaviour
Load app without errors!

### Actual behaviour
An error (`Cannot read property 'style' of undefined`) is thrown upon starting the app. 

Simulator error:
```
<unknown>
Scene.js:30
```

Console error:
```
Cannot read property 'style' of undefined
  handleException @ ExceptionsManager.js:63
  handleError @ InitializeCore.js:114
  reportFatalError @ error-guard.js:44
  guardedLoadModule @ require.js:118
  _require @ require.js:107
  (anonymous) @ require-0.js:1
  executeApplicationScript @ debuggerWorker.js:40
  (anonymous) @ debuggerWorker.js:65
```

This error happened after attempting to update packages, as I haven't worked on this project in quite some time and some of the packages are old versions. After troubleshooting this error I reverted package versions to the original versions and the issue has persisted.

**Comment by zomansud** [comment]
I am facing the same issue. Has anyone able get the project running by rolling back to a previous version. Please suggest.

**Comment by zomansud** [comment]
I fixed it by fixing the version to `3.38.0`

**Comment by scotthollandjr** [comment]
Issue was solved by updating all versions, and removing `^` from RNRF version. Also, clearing cache and deleting `DerivedData` from xcode project, while also deleting the reinstalling the app from the simulator.

```
    "firebase": "4.1.1",
    "lodash": "4.17.4",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.3",
    "react-native-maps": "0.15.2",
    "react-native-router-flux": "3.39.2",
    "react-redux": "5.0.5",
    "realm": "^1.3.1",
    "redux": "3.6.0",
    "redux-thunk": "2.2.0"
```

**Comment by mbenjamin618** [comment]
I am still facing this issue. I am using the latest version (3.41.1). Below is a list of my dependecies. 

```
"dependencies": {
    "@exponent/react-native-responsive-image": "^1.1.0",
    "bad-words": "^1.5.1",
    "crypto-js": "^3.1.9-1",
    "es6-enum": "^1.1.0",
    "inject-tag-style": "^1.1.1",
    "lodash": "^4.16.5",
    "moment": "^2.17.1",
    "next-frame": "^0.2.3",
    "react": "15.4.2",
    "react-addons-perf": "^15.4.2",
    "react-native": "~0.42.0",
    "react-native-atoz-list": "https://github.com/yuana1/react-native-atoz-list.git",
    "react-native-background-upload": "^1.0.0",
    "react-native-bar-collapsible": "^1.5.0",
    "react-native-calendar-events": "github:mikestek/react-native-calendar-events#9457bcba9fc65f694b6eb8aa14d152467e855c85",
    "react-native-code-push": "^1.17.2-beta",
    "react-native-config": "github:mikestek/react-native-config#fb691adf47d812b0318c6cc6a17be8c053fdd3dc",
    "react-native-cookies": "^2.0.0",
    "react-native-device-info": "github:rebeccahughes/react-native-device-info#50e68b4a9766559be6feeb7f7b4a468889ed408b",
    "react-native-dismiss-keyboard": "^1.0.0",
    "react-native-display-html": "github:mbenjamin618/react-native-display-html#8084be980765485669798e9a59901e6ed09e9044",
    "react-native-extra-dimensions-android": "^0.20.1",
    "react-native-fabric": "^0.4.1",
    "react-native-file-provider": "^1.0.2",
    "react-native-fs": "^2.1.0-rc.1",
    "react-native-get-real-path": "^1.0.0",
    "react-native-google-analytics-bridge": "^5.0.1",
    "react-native-http-cache": "github:mbenjamin618/react-native-http-cache#515bcb512863222e31cd57ff7a5e301341b7e958",
    "react-native-i18n": "^0.1.1",
    "react-native-image-picker": "^0.26.3",
    "react-native-inview": "^1.1.2",
    "react-native-keyboard-aware-scroll-view": "^0.2.6",
    "react-native-keyboard-spacer": "^0.3.1",
    "react-native-lightbox": "^0.6.0",
    "react-native-list-view-select": "^1.0.4",
    "react-native-looped-carousel": "github:mbenjamin618/react-native-looped-carousel#d0af173cf5944151869477ef58a138e8d8586a3c",
    "react-native-mail": "^3.0.1",
    "react-native-material-kit": "github:mikestek/react-native-material-kit#d40807f9107ac07ffcd9d5895312d004814bc427",
    "react-native-material-ui": "github:mbenjamin618/react-native-material-ui#e99717fdebaad026b97adf527769df3ef0c2a260",
    "react-native-menu": "^0.20.2",
    "react-native-mimetype": "^0.0.7",
    "react-native-mupdf": "^0.1.33",
    "react-native-orientation": "github:mikestek/react-native-orientation#f1b6d3c70b64affe2fe18e1b70f3f5869cd553a3",
    "react-native-permissions": "^0.2.7",
    "react-native-photo-view": "1.2.0",
    "react-native-push-notification": "github:davearata/react-native-push-notification#b892a2630af0a28ec5b5b74732668c52579e577a",
    "react-native-root-toast": "^1.0.3",
    "react-native-router-flux": "^3.40.0",
    "react-native-share": "github:antmespo/react-native-share#d92669776de263d2691fec29a1d62ab0f150b0eb",
    "react-native-spinkit": "^1.0.2",
    "react-native-stylable": "github:davearata/react-native-stylable#32739ea0ab565150c9610c88ab611a798748dba4",
    "react-native-vector-icons": "^4.0.0",
    "react-native-video": "^1.0.0",
    "react-native-video-player": "^0.6.1",
    "react-native-webhtmlview": "0.0.3",
    "react-native-webkit-localstorage-reader": "github:davearata/react-native-webkit-localstorage-reader#cd8eab4ac5f70e3991b47cd632cd1d76cdc3c5ed",
    "react-native-webview-bridge": "github:davearata/react-native-webview-bridge#b9212dc477a948c75473ba9385680c412d62d2cb",
    "react-redux": "^4.4.6",
    "redux": "^3.6.0",
    "redux-persist": "^4.0.1",
    "redux-persist-transform-filter": "0.0.9",
    "redux-thunk": "^2.1.0",
    "superagent": "^3.3.1",
    "url-parse": "^1.1.7"
  },
  "devDependencies": {
    "babel-eslint": "^7.0.0",
    "babel-plugin-flow-react-proptypes": "^0.20.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "babel-preset-stage-0": "^6.24.1",
    "chai": "^3.5.0",
    "chai-as-promised": "^6.0.0",
    "chai-enzyme": "^0.5.2",
    "cheerio": "^0.22.0",
    "colors": "^1.1.2",
    "debug": "2.2.0",
    "enzyme": "^2.5.1",
    "eslint": "^3.8.1",
    "eslint-config-standard": "^6.2.0",
    "eslint-config-standard-react": "^4.2.0",
    "eslint-plugin-flowtype": "^2.29.1",
    "eslint-plugin-promise": "^3.3.0",
    "eslint-plugin-react": "^6.4.1",
    "eslint-plugin-standard": "^2.0.1",
    "flow-bin": "^0.38.0",
    "fs-extra": "^0.30.0",
    "gulp": "^3.9.1",
    "istanbul": "^1.1.0-alpha.1",
    "lint-staged": "^3.2.1",
    "minimist": "^1.2.0",
    "mocha": "^3.1.2",
    "nock": "^9.0.2",
    "pre-commit": "^1.1.3",
    "pre-push": "^0.1.1",
    "promised-spawn": "0.0.1",
    "react-addons-test-utils": "^15.3.2",
    "react-devtools": "^2.0.12",
    "react-dom": "^15.3.2",
    "react-native-mock": "^0.2.7",
    "react-stub-context": "^0.7.0",
    "require-dir": "^0.3.1",
    "run-sequence": "^1.2.2",
    "sinon": "^1.17.6"
  }
}
```

**Comment by sarahmarciano** [comment]
@mbenjamin618 did u solve it??
I have the latest version and I am still hitting this error.
Any idea?

**Comment by gregjw** [comment]
I have the latest version and I'm still getting this error.
Was any solution found?

**Comment by ersanjay5991** [comment]
I have same Issue cant find it 
```
{
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "axios": "^0.21.4",
    "expo": "~42.0.1",
    "expo-splash-screen": "~0.11.2",
    "expo-status-bar": "~1.0.4",
    "expo-updates": "~0.8.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "^0.65.1",
    "react-native-elements": "^3.4.2",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-reanimated": "~2.2.0",
    "react-native-router-flux": "^3.36.0",
    "react-native-screens": "~3.4.0",
    "react-native-unimodules": "0.14.10",
    "react-native-web": "^0.17.1"
  },

```
