### ISSUE TITLE
Reset stack on enter Scene?

### ISSUE THREAD

**Issue by luco** [aksonov/react-native-router-flux#2104]
Is it possible to reset the stack when entering on a scene?
I mean, I want to push from a scene to tabbar, but when reach the tabbar, reset the stack.

Is that possible?

I already tried `Actions.homeMain({type: ActionConst.RESET})`

Didn't work.

**Comment by alexwasner** [comment]
One way to do it on a route is to just put `type='reset'` in the `Scene`, but that doesnt allow you to call a reset when you navigate. I too would like to know the new standard for doing this

**Comment by luco** [comment]
@alexwasner Tried that. Didn't work.

**Comment by rajsuvariya** [comment]
@luco Actions.homeMain({type: ActionConst.RESET}) this was working in v3 of react-native-router-flux. But the current version v4 is based on React Navigator so there are syntax changes. For resetting back stack you can try Actions.reset("homeMain")

**Comment by aksonov** [comment]
Looks like `{type: ActionConst.RESET}` calls 'replace' now. I've just fixed it for latest master

**Comment by aksonov** [comment]
@luco Have you tried `type='reset'` for tab bar?

**Comment by luco** [comment]
@aksonov Still not working. Tried both `type='replace'` and `{type: ActionConst.RESET}`.
Should I remove the plugin and add again?

![untitled-1](https://user-images.githubusercontent.com/246373/28573347-c5db8aae-7120-11e7-8a5c-a21aa0d0f031.png)

**Comment by rajsuvariya** [comment]
@luco In my case Actions.reset("homeMain") is working. Try that.

**Comment by aksonov** [comment]
@luco Could you reproduce it with latest Example? I used Actions.tabbar({type:'replace'}) with 4.0.0-beta.14 and tabbar replaces launch screen normally.

**Comment by luco** [comment]
@aksonov It gives me this error:

![image](https://user-images.githubusercontent.com/246373/28575949-cbfe21dc-7128-11e7-9aa5-afdaea0295da.png)

My structure is like this:

```
<Scene key="root" hideNavBar initial>

                  <Scene key="welcome">
                      <Scene key="welcome1" title="" hideNavBar component={Welcome}/>
                  </Scene>

                  <Scene key="tabbar" 
                  tabBarPosition={'bottom'}
                  tabs 
                  showLabel={false} 
                  {...sceneConfig} 
                  tabBarComponent={this.tabBarElement.bind(this)}
                 >

                        <Scene key="home" type="reset" {...sceneConfig}>
                          <Scene key="homeMain" component={Home}/>
...

```

**Comment by aksonov** [comment]
Remove type='reset' from scenes. Use it as parameter. Again, please reproduce it with current Example project.

**Comment by rajsuvariya** [comment]
@aksonov is this incorrect Actions.reset("homeMain") ? I am able to reset the back stack using it.

**Comment by luco** [comment]
@rajsuvariya When I try this method, it only allows me to pick scenes outside my root.

**Comment by luco** [comment]
@aksonov Ok, you want to reproduce with example project, but this doesnt solve my problem. I want to understand what im doing wrong.

**Comment by luco** [comment]
@aksonov Figured it out. It was the way my Scenes where nested. Had to do this way:
```

<Scene key="start">
                    <Scene key="welcome">
                        <Scene key="welcome1" title="" hideNavBar component={Welcome}/>
                    </Scene>
                        ...
                    <Scene key="root" hideNavBar>

                        <Scene key="tabbar" ...
```

**Comment by aksonov** [comment]
Try type='replace'

**Comment by luco** [comment]
I'm getting a warning of maximum call stack when I perform a `Actions.root({type: ActionConst.RESET});`, but nothing with `Actions.root()`.

Do you have idea why?

**Comment by luco** [comment]
Nervemind. Typo.
Thanks!

**Comment by kumarpatel** [comment]
@luco Given your routing structure:
```

      <Router>
        <Scene key="root" hideNavBar>

          <Scene key="welcome">
            <Scene key="welcome1" title="" hideNavBar component={Welcome} />
          </Scene>

          <Scene key="tabbar" tabBarPosition={'bottom'} tabs >

            <Scene key="home" type="reset" {...sceneConfig}>
              <Scene key="homeMain" component={Home}/>
            </Scene>

          </Scene>
        </Scene>

      </Router>
```

How did you reset the stack when navigating from
1. welcome1 -> homeMain (presumably when logging in, ¯\_(ツ)_/¯)
2. homeMain -> welcome1 (presumably when logging out, ¯\_(ツ)_/¯)

**Comment by anasmonsha** [comment]
try type: 'replace'

**Comment by kalraneeraj24550** [comment]
thanks @aksonov sir, your solution worked for me.

**Comment by robleds** [comment]
> @luco In my case Actions.reset("homeMain") is working. Try that.

Tks @rajsuvariya  works for me !
