### ISSUE TITLE
onEnter not being executed when using Actions.pop() manually

### ISSUE THREAD

**Issue by rajsuvariya** [aksonov/react-native-router-flux#2147]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.12
- react-native v0.46.3

### Expected behavior
When I press "Add" button I am calling Actions.pop() and Actions.refresh({data: this.state.mydata}). In this case, when the previous screen becomes visible onEnter callback should be executed.

### Actual behavior
When I press "Add" button I am calling Actions.pop() and Actions.refresh({data: this.state.mydata}). In this case, when the previous screen becomes visible onEnter callback is not being executed. It is being executed when I press back or Android hardware back button from second component.

### Steps to reproduce
1. Project with two component
2. Add onEnter and onExit callbacks with console.log() in first component's scene inside router.
3. Add a button to open the second component from first component. (call Actions.openSecondComp())
4. In the second component add a button "Add" and on the press of this button call 
   ```
    Actions.pop();
    Actions.refresh({data: "Random String"});
    ```
5. Check console logs. onEnter is not being executed.

**Comment by aksonov** [comment]
Please check latest master branch. If it still exists, try to reproduce on this repo Example project.

**Comment by rajsuvariya** [comment]
After taking clone of master even onExit is not working when I open the new screen using Actions.secondComp().

I have added onEnter and onExit props in `loginModal` in the Example.js in this repo https://github.com/rajsuvariya/react-native-router-flux Please check

**Comment by rajsuvariya** [comment]
![video](https://user-images.githubusercontent.com/12663795/28781338-585bf94e-7627-11e7-974c-2d5398125741.gif)

**Comment by aksonov** [comment]
So only onExit doesn't work properly, right?

**Comment by rajsuvariya** [comment]
Yes

**Comment by aksonov** [comment]
Please check latest master, it should be fixed

**Comment by rajsuvariya** [comment]
Okay

**Comment by rajsuvariya** [comment]
No, it isn't fixed yet.

![image](https://user-images.githubusercontent.com/12663795/28828219-a42ff070-76ed-11e7-9232-f9c3caca377d.png)

**Comment by rajsuvariya** [comment]
No, It isn't fixed yet.

![image](https://user-images.githubusercontent.com/12663795/28828289-ea5f86be-76ed-11e7-9666-42422aba812e.png)

**Comment by rajsuvariya** [comment]
No, It isn't fixed yet.

![image](https://user-images.githubusercontent.com/12663795/28828337-13b8ce9e-76ee-11e7-9783-4b52f688a9b0.png)

**Comment by aksonov** [comment]
How did you test it? Are you sure that you are using latest master (not just Example from master) ?

**Comment by rajsuvariya** [comment]
I am using your example project only and yes I took pull from master not Example project (see the image)

![image](https://user-images.githubusercontent.com/12663795/28829554-c7703348-76f1-11e7-976b-752570f3bbd3.png)

**Comment by aksonov** [comment]
Example uses beta.15 not latest master, that is why I asked you to change RNRF inside Example to latest one.

**Comment by rajsuvariya** [comment]
I am sorry about that. 

But as I am new to open source I don't know how to use the source code directly. Can you please tell me how to do it?

**Comment by aksonov** [comment]
Ok, please check latest now, I've modified dependencies directly to latest master

**Comment by rajsuvariya** [comment]
Yes, It's working perfectly. Thanks a lot.
