### ISSUE TITLE
Left Back button color

### ISSUE THREAD

**Issue by ajoshdee** [aksonov/react-native-router-flux#276]
How do you change the color of the back button?  leftButtonStyle={{color:'white'}} is not working either in router and route.

**Comment by marcelglaeser** [comment]
+1

**Comment by codebreach** [comment]
+1

**Comment by marcelglaeser** [comment]
I'm created a custom button. it solved that.

**Comment by aksonov** [comment]
Please check latest release, it should be fixed

**Comment by SudoPlz** [comment]
How did you guys manage to change the color of the leftButton? `leftButtonStyle={{color:'white'}}` is still not working for me.

**Comment by RWOverdijk** [comment]
@aksonov I tried applying this, it doesn't work. I used both `leftButtonTextStyle` and `leftButtonStyle`, the arrow is still some sort of blue.

<img width="145" alt="screenshot 2016-03-27 23 47 55" src="https://cloud.githubusercontent.com/assets/781745/14068012/5d13847c-f476-11e5-8550-9a38ea72303e.png">

Any direction in which I can look for a solution? Or do you perhaps already know what I', doing wrong? :)

I'm on version `^3.2.3`

**Comment by kesha-antonov** [comment]
@RWOverdijk Try this on your scene/scenes: `barButtonIconStyle={{tintColor: 'black'}}`

**Comment by aksonov** [comment]
@RWOverdijk Because arrow is blue image, you can't change its color. You could set your image there or submit PR to replace image with some vector graphics using ReactNativeART for example...

**Comment by RWOverdijk** [comment]
Already did, and already got merged, too. :) I should've commented that here, my bad.

Thanks for the help!
