### ISSUE TITLE
The second click on Tab doesn't work on Android

### ISSUE THREAD

**Issue by faycito** [aksonov/react-native-router-flux#3496]
### Version

- react-native-router-flux v4.0.6
<!--
Please before continuing, check if the versions that you using are compatible.

### Expected behavior

Click on  tab and swipe on tab screen anytime

### Actual behaviour
Click on a tab and swipe only the first time, when I click to second time it doesn't work

### Steps to reproduce
click on tap and then click to another tab

**Comment by hanishcodebrew** [comment]
I facing the same issue

I recently updated my old project from **0.55.4** to **0.59.5**.Its working fine in iOS Release & Debug along with Android Debug. but in **Android release mode** switching between tabs is not working properly. 
I am using react-native-router-flux in that old project

**Current version of react native router flux**  react-native-router-flux v4.0.6

Please help :)

**Comment by Assgcbl** [comment]
same issue as @hanishcodebrew

**Comment by hanishcodebrew** [comment]
For more detail check the link below 

[](https://stackoverflow.com/questions/57704002/react-native-router-flux-tabs-on-press-is-not-working-after-select-any-tab)

**Comment by hanishcodebrew** [comment]
@faycito Did you find any solution for this?

**Comment by hanishcodebrew** [comment]
So, finally after huge struggle. I fixed this issue myself.

First of all, I deleted the node module folder (Please take backup before doing this step). Then, I installed node modules again via

npm install command

After that, I got some issues regarding androidx in some packages, I fixed those using

npm install --save-dev jetifier npx jetify npx react-native run-android (your app should correctly compile and work)

Also add

```
android.useAndroidX=true
android.enableJetifier=true
```
in your gradle.properties file

After these steps and removing the androidx related issues. I created release apk, installed it and everything was working fine.

**Comment by mikaoelitiana** [comment]
I had same issue as @hanishcodebrew, unfortunately your solution didn't fix it for me.
