### ISSUE TITLE
For Actions.replace() and Actions.reset() animated transition is happening

### ISSUE THREAD

**Issue by kolarus** [aksonov/react-native-router-flux#3741]
### Version
- react-native-router-flux v4.3.0
- react-native v0.63.4
- react: 16.13.1

### Expected behaviour
When using `Actions.replace()` or `Actions.reset()` no animated transition should occur

### Actual behaviour
Animated transition happens 

### Platform
IOS (Not tested on android yet)

**Comment by oleksandr-dziuban** [comment]
Same issues after migration to 4.3.0 from 4.2.0, @aksonov Could you please check? Thanks!

**Comment by aksonov** [comment]
Please check latest master

**Comment by oleksandr-dziuban** [comment]
> Please check latest master

Great, thanks, could you please deploy fix to latest nam package?

**Comment by minuitagency** [comment]
Hi @aksonov , thank you for the quick fix, I still have a transition animation when using Actions.reset() in 4.3.1, is there something I missed or a dependency that I should update? 

Thanks

**Comment by aksonov** [comment]
Do you have animation in react-native/Example for Register replace screen?

**Comment by minuitagency** [comment]
@aksonov just checked your code, the "type" prop was undefined that's why the animation loaded, I patched it with:

`      animationEnabled: (type === ActionConst.REPLACE || type === 'replace' || !type) ? false : true,
`

It works for me now

**Comment by aksonov** [comment]
Hm, this will broke 'push' type animations..

**Comment by minuitagency** [comment]
oh... what should I do? Why is "type" undefined ?

**Comment by Yhnlvy** [comment]
Following

**Comment by aksonov** [comment]
Could you reproduce the issue with react-native/Example project?

**Comment by ebaynaud** [comment]
Sounds normal to have animations with replace and reset now according to [this](https://github.com/react-navigation/stack/releases/tag/v2.0.1), no? Question is: how do we disabled the animation to reproduce the old behaviour?

**Comment by oleksandr-dziuban** [comment]
Issue fixed, thanks a lot

**Comment by kolarus** [comment]
Fixed, thanks!

**Comment by oleksandr-dziuban** [comment]
@aksonov Hello, issue still exists, are you planning to resolve it and deploy new patch version? Thansk a lot

**Comment by kolarus** [comment]
Reopening, just checked, we still have animations

**Comment by ebaynaud** [comment]
Linked to https://github.com/react-navigation/stack/releases/tag/v2.0.1 ?

**Comment by pacoyang** [comment]
Same issue on 4.3.1

**Comment by yogendrajs** [comment]
The issue still persists, does someone have an idea how to resolve this?
