### ISSUE TITLE
Hide TabBar

### ISSUE THREAD

**Issue by sslash** [aksonov/react-native-router-flux#52]
Say I have a Route that is a part of a TabBar. Is it possible to remove/hide the tabbar (i.e fullscreen) when I go to that particular route?

<img width="262" alt="app__-_google_drive" src="https://cloud.githubusercontent.com/assets/1174520/11726774/840c908c-9f80-11e5-93b2-1d1d41d47919.png">

The tabbar can be seen in the bottom. I want to remove it when I go to the route that is triggered when I press the button in the middle.

**Comment by erdostom** [comment]
:+1:

**Comment by aksonov** [comment]
try latest 1.0.3 and hideTabBar for Route component (Wanted: person who will write docs :)

**Comment by sslash** [comment]
nice! but if you go back, it is now gone forever :( I can try and write some docs!

**Comment by aksonov** [comment]
oops, will check.

**Comment by aksonov** [comment]
@sslash Should work now with latest release, it was bigger problem - tab bar was not updated if you switched externally, not via tabbar but from button or somewhere else.

**Comment by sslash** [comment]
nice. Though it seems like the selected property is now broken

**Comment by joshuarotenberg** [comment]
@aksonov: I'm updated to the latest version and I've added `hideTabBar={true}` to my route inside the tabbar and it does not work. I can pull the route out of the tabbar component but then I lose navigation. Thoughts?

**Comment by aksonov** [comment]
I can't reproduce. Make sure you are using latest version, i've updated package.json for demo now

**Comment by aksonov** [comment]
Hiding tab bar is not working for nested routes (i.e. start route doesn't have hideTabBar, but next one (pushed) have this, tab bar will not be hidden)

**Comment by aksonov** [comment]
should work with 2.0.5, please check demo, tab n2

**Comment by paulbao** [comment]
@aksonov 'Hiding tab bar is not working for nested routes (i.e. start route doesn't have hideTabBar, but next one (pushed) have this, tab bar will not be hidden)' Is this fixed?
I am now try version 2.1.4 and just add hideTabBar={true} like below. But it seems not working.
<Route name="tab2_1" component={TabView} title="Tab #2_1" hideTabBar={true}/>

**Comment by aksonov** [comment]
Check Example, second tab is hidden.

**Comment by paulbao** [comment]
Yes, I've checked Example and only Navigation bar is hidden for the second tab not Tab bar.

**Comment by aksonov** [comment]
Looks like other changes broke it. It definitely worked with 2.0.5..

**Comment by aksonov** [comment]
Should work now, with latest 2.2.2

**Comment by paulbao** [comment]
Thanks @aksonov , the example works well, but if I add hideTab={true} 
`<Route name="tab2_2" component={TabView} title="Tab #2_2 hideTabBar={true}" />`. It still doesn't work.

**Comment by aksonov** [comment]
Your title doesn't have quote closed...

**Comment by paulbao** [comment]
Have you tried `<Route name="tab2_2" component={TabView} title="Tab #2_2" hideTabBar={true} />` ?
To be honest, It's just a typo that I am trying to explain this issue by your provided example. hideTabBar is still not working for both my own project and your Example.

**Comment by aksonov** [comment]
I will do when will have time, so it doesn't work only for tab#2? looks very strange.

**Comment by paulbao** [comment]
Thanks for your time. I think it's not working for nested Route. In another word, it works for tab1 and tab2, but not work for tab1_2 and tab2_2

**Comment by KBLNY** [comment]
I confirmed that even the latest master release (2.2.6) doesn't fix this.
@aksonov Btw, a big thank for your initiative, :+1: for the way you designed the route and router management.

**Comment by kesha-antonov** [comment]
Need this too: hide tab bar for nested route.

**Comment by aksonov** [comment]
3.0 is released, please check it there. Closing it for now, because it is for outdated version (2.x)

**Comment by jamesone** [comment]
Did this ever get resolved? I can't use 3.x cos of other modules needing a lower version of React-native.

**Comment by brien-crean** [comment]
I'm wondering the same as @jamesone, anyone ever figure out a workaround?

**Comment by jamesone** [comment]
@brien-crean  - Haven't found one yet. Would be extremely useful though.

**Comment by micahkatz** [comment]
In ^4.0.0-beta.26, you can just put `hideTabBar={true}` on any scene and it will hide the tab bar for that scene or for the whole navigation inside of that scene

**Comment by j-funk** [comment]
This is not working for me in v4.0.1.  The `hideNavBar` prop works on any nested Scene, but not `hideTabBar`.

```
        <Stack
          key="home"
          title={AppConfig.appName.toUpperCase()}
          icon={() => <Icon name="planet" {...DefaultProps.icons} />}
          {...DefaultProps.navbarProps}
        >
          <Scene key="home" component={AboutComponent} />
          <Scene
            hideTabBar
            hideNavBar
            key="designer"
            title="DESIGNER"
            component={DesignerContainer}
            Layout={DesignerComponent}
          />
        </Stack>
```

**Comment by th3d0g** [comment]
FYI - in "react-native-router-flux": "4.0.6" I had to add 'hideTabBar={true}' to the <Stack>, not <Scene> for it to work.

@j-funk not sure if the same is the case in 4.0.1

**Comment by ramanasak** [comment]
hideTabBar={true}  // to hide Tab bar

<Scene key="home"   hideNavBar={true} component={Home} title="Home" hideTabBar={true}   />

this should work.

**Comment by IndianNative** [comment]
Hi Guys any update on this
