### ISSUE TITLE
Example Application error

### ISSUE THREAD

**Issue by fultonm** [aksonov/react-native-router-flux#640]
Running the Example application on with react-native run-android:

Application Example has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.

Still learning react native.

**Comment by charpeni** [comment]
You're right, something went wrong with the example. I'm on it.

**Comment by charpeni** [comment]
I just merged a fix into `master`, just grab the last version and you should be able to run the example.

Sorry for this inconvenience, if it doesn't fixed your issue just reopen it.

Happy learning !

**Comment by fultonm** [comment]
Looks good for the Example app!

I'm still getting the same error message in my separate app, though. This error message can point to errors in Example.js and beyond? I'm using Chrome debugging tools to find out whats wrong but there's not a lot of informative debugging info.

**Comment by loopdtw** [comment]
this problem still seems to be occurring? I'm not able to run the example code at all

**Comment by sebfie** [comment]
Hello, I still have the same issue!

**Comment by SXCYF** [comment]
This issue is still at there. I want to view the example, who can help me?
